namespace RentMe.Model;

/// <summary>
/// Category model class
/// </summary>
public class Category
{
    // Standard autogenerated getter/setters


    public int CategoryID { get; set; }
    public string Name { get; set; }
}