namespace RentMe.Model;

/// <summary>
/// Employee model class
/// </summary>
public class Employee
{
    // Standard autogenerated getter/setters
    public int EmployeeID { get; set; } 
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Sex { get; set; }
    public DateTime DateOfBirth { get; set; }
    public string Phone { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public string State { get; set; }
    public string Zip { get; set; }
    public string UserName { get; set; }
    public string Password { get; set; }

    /// <summary>
    /// Gets or sets a value indicating whether this instance is admin.
    /// </summary>
    /// <value>
    ///   <c>true</c> if this instance is admin; otherwise, <c>false</c>.
    /// </value>
    public Boolean IsAdmin { get; set; }

}