namespace RentMe.Model;

/// <summary>
/// Furniture model class
/// </summary>
public class Furniture
{
    // Standard autogenerated getter/setters


    public int dbo { get; set; }
    public int FurnitureID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int QuantityOwned { get; set; }
    public int QuantityRented { get; set; }
    public int DailyRentalRate { get; set; }
    public int CategoryID { get; set; }
    public int StyleID { get; set; }
}