namespace RentMe.Model;

/// <summary>
/// Furniture model class
/// </summary>
public class Furniture
{
    // Standard autogenerated getter/setters


    public int dbo { get; set; }
    public int FurnitureID { get; set; }
    public string Name { get; set; }
    public string Description { get; set; }
    public int QuantityOwned { get; set; }
    public int QuantityRented { get; set; }
    public decimal DailyRentalRate { get; set; }
    public string Category { get; set; }
    public string Style { get; set; }
}