
namespace RentMe.Model
{
    /// <summary>
    /// Member model class
    /// </summary>
    internal class Member
    {
        // Standard autogenerated getter/setters

        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Sex { get; set; }
        public DateTime DateOfBirth { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
    }
}
