using RentMe.Controller;
using RentMe.DAL;
using System.ComponentModel;
using System.Data;

namespace RentMe.Model;

/// <summary>
/// RentalTransaction model class
/// </summary>
public class RentalTransaction
{
    private RentalLineItem _rentalLineItems;
    private FurnitureDAL _furnitureDAL;

    public RentalTransaction()
    {
        this._rentalLineItems = new RentalLineItem();
        this._furnitureDAL = new FurnitureDAL();
    }

    // Standard autogenerated getter/setters

    public int RentalID { get; set; }
    public DateTime DateRented { get; set; }
    public DateTime DateDue { get; set; }
    public int EmployeeID { get; set; }
    public int MemberID { get; set; }

    public RentalLineItem RentalLineItems
    {
        get => this._rentalLineItems;
    }

    /// <summary>
    /// Adds the line item.
    /// </summary>
    /// <param name="lineItem">The line item.</param>
    public void AddLineItem(int furnitureID, int quantity)
    {
        Furniture furniture = this._furnitureDAL.GetFurnitureByID(furnitureID);

        ArgumentNullException.ThrowIfNull(furniture);

        DataRow workRow = _rentalLineItems!.GetDataTable().NewRow();
        workRow["FurnitureID"] = furnitureID;
        workRow["Name"] = furniture.Name;
        workRow["Description"] = furniture.Description;
        workRow["QuantityOwned"] = furniture.QuantityOwned;
        workRow["QuantityRented"] = furniture.QuantityRented;
        workRow["DailyRentalRate"] = furniture.DailyRentalRate;
        workRow["Category"] = furniture.Category;
        workRow["Style"] = furniture.Style;
        workRow["Quantity"] = quantity;

        _rentalLineItems.GetDataTable().Rows.Add(workRow);
    }

    /// <summary>
    /// Removes the line item.
    /// </summary>
    /// <param name="furnitureID">The furniture identifier.</param>
    public void RemoveLineItem(int furnitureID)
    {
        var rows = _rentalLineItems!.GetDataTable().Select($"FurnitureID = {furnitureID}");

        foreach (var row in rows)
        {
            row.Delete();
        }

        _rentalLineItems!.GetDataTable().AcceptChanges();
    }

    /// <summary>
    /// Clears the line items.
    /// </summary>
    public void ClearLineItems()
    {
        this._rentalLineItems.GetDataTable().Clear();
    }
}