namespace RentMe.Model;

/// <summary>
///  RentalLineItem model class
/// </summary>
public class RentalLineItem
{
    // Standard autogenerated getter/setters

    public int RentalID { get; set; }  // Should we get this from the RentalTransaction?
    public int FurnitureID { get; set; }
    public int Quantity { get; set; }
}