using RentMe.Controller;
using System.ComponentModel;

namespace RentMe.Model;

/// <summary>
/// RentalTransaction model class
/// </summary>
public class RentalTransaction
{
    private List<RentalLineItem> _rentalLineItems;

    public RentalTransaction()
    {
        this._rentalLineItems = new List<RentalLineItem>();
    }

    // Standard autogenerated getter/setters

    public int RentalID { get; set; }
    public DateTime DateRented { get; set; }
    public DateTime DateDue { get; set; }
    public int EmployeeID { get; set; }
    public int MemberID { get; set; }

    public List<RentalLineItem> RentalLineItems
    {
        get => this._rentalLineItems;
    }

    /// <summary>
    /// Adds the line item.
    /// </summary>
    /// <param name="lineItem">The line item.</param>
    public void AddLineItem(int furnitureID, int quantity)
    {
        RentalLineItem lineItem = new RentalLineItem
        {
            FurnitureID = furnitureID,
            Quantity = quantity
        };

        this._rentalLineItems.Add(lineItem);
    }

    /// <summary>
    /// Removes the line item.
    /// </summary>
    /// <param name="furnitureID">The furniture identifier.</param>
    public void RemoveLineItem(int furnitureID)
    {
        this._rentalLineItems = this._rentalLineItems.Where(lineItem => lineItem.FurnitureID != furnitureID).ToList();
    }

    /// <summary>
    /// Clears the line items.
    /// </summary>
    public void ClearLineItems()
    {
        this._rentalLineItems.Clear();
    }
}