using System.ComponentModel;

namespace RentMe.Model;

/// <summary>
/// ReturnTransaction model class
/// </summary>
public class ReturnTransaction
{
    // Standard autogenerated getter/setters

    public int ReturnID { get; set; }
    public DateTime DateReturned { get; set; }
    public int EmployeeID { get; set; }
    public int MemberID { get; set; }
    public BindingList<ReturnLineItem> LineItems { get; set; }
}