namespace RentMe.Model;

/// <summary>
/// Style model class
/// </summary>
public class Style
{
    // Standard autogenerated getter/setters


    public int StyleID { get; set; }
    public string Name { get; set; }
}